run:
  timeout: 15m

output:
  sort-results: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - staticcheck
    - unused
    - goimports

issues:
  max-same-issues: 0

linters-settings:
  goimports:
    local-prefixes: github.com/raeperd/test
